# Generated by Django 3.2.9 on 2021-11-17 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cli', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='secret_key',
            field=models.CharField(blank=True, default='ykhgLwEnnD', max_length=40),
        ),
        migrations.AlterField(
            model_name='user',
            name='certificate',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='cli.certificate', verbose_name='Cертификат пользователя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='certificates',
            field=models.ManyToManyField(blank=True, null=True, related_name='subject_user', to='cli.Certificate', verbose_name='Сертификаты субъектов'),
        ),
    ]
