# Generated by Django 3.2.9 on 2021-11-18 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cli', '0002_auto_20211117_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='private_key',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='secret_key',
            field=models.CharField(blank=True, default='8VWqHgLLXv', max_length=40),
        ),
    ]
