# Generated by Django 3.2.9 on 2021-11-18 16:16

import cli.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cli', '0003_auto_20211118_1545'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', cli.manager.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='private_key',
            field=models.FileField(blank=True, null=True, upload_to='private_key'),
        ),
        migrations.AlterField(
            model_name='user',
            name='secret_key',
            field=models.CharField(blank=True, default='tR75bgj8V4', max_length=40),
        ),
    ]
