# Generated by Django 3.2.9 on 2021-11-18 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cli', '0004_auto_20211118_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='secret_key',
            field=models.CharField(blank=True, default='MN8JxacAGA', max_length=40),
        ),
    ]
