# Generated by Django 3.2.9 on 2021-11-18 16:50

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cli', '0006_alter_user_secret_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='secret_key',
            field=models.CharField(blank=True, default='r4WA5nkc3n', max_length=40),
        ),
    ]
