# Generated by Django 3.2.9 on 2021-11-20 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cli', '0009_auto_20211120_1259'),
    ]

    operations = [
        migrations.CreateModel(
            name='Key',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_key', models.FileField(upload_to='public')),
                ('private_key', models.FileField(upload_to='private')),
                ('active', models.BooleanField(blank=True, default=True)),
                ('type', models.CharField(choices=[('Ключ регистрационного центра', 'Reg'), ('Ключ сертификационного центра', 'Cert')], max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='secret_key',
            field=models.CharField(blank=True, default='XqhFXRDGwq', max_length=40),
        ),
    ]
