# Generated by Django 3.2.9 on 2021-11-23 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cli', '0011_auto_20211120_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='secret_key',
            field=models.CharField(blank=True, default='JbVxdGBaK2', max_length=40),
        ),
    ]
