# Generated by Django 3.2.9 on 2021-11-30 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cli', '0013_auto_20211124_1456'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_file', models.FileField(blank=True, null=True, upload_to='source_file')),
                ('new_file', models.FileField(blank=True, null=True, upload_to='new_file')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='secret_key',
            field=models.CharField(blank=True, default='wMKrGLth3V', max_length=40),
        ),
    ]
