# Generated by Django 3.2.9 on 2021-11-05 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='As',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_serial_number', models.CharField(max_length=50, verbose_name='Серийный номер сертификата')),
                ('revocation_date', models.DateTimeField(verbose_name='Дата получения запроса об аннулировании')),
                ('reason_code', models.CharField(choices=[('1', 'Причина не определена'), ('2', 'Повреждение ключа конечного пользователя'), ('3', 'Повреждение ключа УЦ'), ('4', 'Изменение информации в сертификате(не повреждение)'), ('5', 'Приостановление действия ключа'), ('6', 'Завершение использования'), ('7', 'Приостановление использования'), ('8', 'Отмена временного приостановления')], max_length=5, verbose_name='Код причины аннулирования')),
                ('hold_instruction_code', models.CharField(max_length=20, verbose_name='Код временного приостановления сертификата (OID)')),
                ('invalidity_date', models.DateTimeField(verbose_name='Дата признания сертификата недействительным')),
                ('certificate_issuer', models.CharField(max_length=50, verbose_name='Имя издателя сертификата, ассоциированного с косвенным САС')),
            ],
            options={
                'verbose_name': 'Аннулированный сертификат',
                'verbose_name_plural': 'Аннулированные сертификаты',
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(blank=True, default='1', max_length=20, verbose_name='Версия сертификата')),
                ('serial_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Серийный номер сертификата')),
                ('id_algorithm_signature', models.CharField(blank=True, max_length=50, null=True, verbose_name='Идентификатор алгоритма цифровой подписи')),
                ('publisher_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Имя издателя')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='Дата начала действия сертификата')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Дата конца действия сертификата')),
                ('subject_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Имя субъекта сертификата')),
                ('public_key', models.CharField(blank=True, max_length=200, null=True, verbose_name='Публичный ключ субъекта')),
                ('id_publisher', models.CharField(blank=True, max_length=200, null=True, verbose_name='Уникальный идентификатор издателя')),
                ('id_subject', models.CharField(blank=True, max_length=200, null=True, verbose_name='Уникальный идентификатор субъекта')),
            ],
            options={
                'verbose_name': 'Сертификат',
                'verbose_name_plural': 'Сертификаты',
            },
        ),
        migrations.CreateModel(
            name='Key',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_key', models.FileField(upload_to='public')),
                ('private_key', models.FileField(upload_to='private')),
                ('active', models.BooleanField(blank=True, default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Имя субъекта')),
                ('secret_key', models.CharField(blank=True, max_length=50, null=True, verbose_name='Секретный ключ субъекта(для подтверждения личности)')),
            ],
            options={
                'verbose_name': 'Субъект',
                'verbose_name_plural': 'Субъекты',
            },
        ),
        migrations.CreateModel(
            name='Sas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(blank=True, default='1', max_length=20, verbose_name='Версия сертификата')),
                ('id_algorithm_signature', models.CharField(blank=True, max_length=50, null=True, verbose_name='Идентификатор алгоритма цифровой подписи')),
                ('issuer', models.CharField(max_length=50, verbose_name='Уникальное имя УЦ-издателя САС')),
                ('this_update', models.DateTimeField(verbose_name='Дата выпуска данного САС')),
                ('next_update', models.DateTimeField(verbose_name='Планируемая дата следующего САС')),
                ('authority_key_identifier', models.CharField(max_length=50, verbose_name='Идентификатор ключа, используемого для подтверждения САС')),
                ('crl_number', models.CharField(max_length=50, verbose_name='Серийный номер списка аннулированных сертификатов')),
                ('issuing_distribution_point', models.CharField(max_length=200, verbose_name='Атрибуты выпускающего пункта распространения САС')),
                ('delta_crl_indicator', models.CharField(max_length=200, verbose_name='Индикатор разностного списка аннулированных сертификатов (дельта-списка)')),
                ('certificate', models.ManyToManyField(related_name='sas', to='reg.As')),
            ],
            options={
                'verbose_name': 'Список аннулированных сертификат',
                'verbose_name_plural': 'Списки аннулированных сертификатов',
            },
        ),
    ]
