# Generated by Django 3.2.9 on 2021-11-05 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryGetKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=50, verbose_name='Имя субъекта')),
                ('object_name', models.CharField(max_length=50, verbose_name='Имя объекта')),
                ('attempt_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'История запроса на публичный ключ',
                'verbose_name_plural': 'История запросов на ппубличные ключи',
            },
        ),
        migrations.CreateModel(
            name='HistoryRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=50, verbose_name='Имя субъекта')),
                ('attempt_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(blank=True, default=True)),
                ('certificate_serial_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Серийный номер сертификата')),
            ],
            options={
                'verbose_name': 'Попытка регистрации',
                'verbose_name_plural': 'Попытки регистрации',
            },
        ),
    ]
