# Generated by Django 3.2.9 on 2021-11-05 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0002_historygetkey_historyregistration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historygetkey',
            options={'verbose_name': 'История запроса на публичный ключ', 'verbose_name_plural': 'История запросов на публичные ключи'},
        ),
        migrations.RemoveField(
            model_name='historygetkey',
            name='object_name',
        ),
        migrations.RemoveField(
            model_name='historygetkey',
            name='subject_name',
        ),
        migrations.RemoveField(
            model_name='historyregistration',
            name='subject_name',
        ),
        migrations.AddField(
            model_name='historygetkey',
            name='object',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='objects', to='reg.subject', verbose_name='Имя объекта'),
        ),
        migrations.AddField(
            model_name='historygetkey',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='reg.subject', verbose_name='Имя субъекта'),
        ),
        migrations.AddField(
            model_name='historyregistration',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reg.subject', verbose_name='Имя субъекта'),
        ),
    ]
