# Generated by Django 3.2.9 on 2021-11-06 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0003_auto_20211105_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='address',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Сетевой адрес субъекта'),
        ),
        migrations.AlterField(
            model_name='as',
            name='certificate_issuer',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Имя издателя сертификата, ассоциированного с косвенным САС'),
        ),
        migrations.AlterField(
            model_name='as',
            name='hold_instruction_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Код временного приостановления сертификата (OID)'),
        ),
        migrations.AlterField(
            model_name='as',
            name='invalidity_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата признания сертификата недействительным'),
        ),
        migrations.AlterField(
            model_name='as',
            name='revocation_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата получения запроса об аннулировании'),
        ),
        migrations.AlterField(
            model_name='historyregistration',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='reg.subject', verbose_name='Имя субъекта'),
        ),
    ]
