# Generated by Django 3.2.9 on 2021-11-06 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0004_auto_20211106_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='subject_name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Имя субъекта'),
        ),
    ]
