# Generated by Django 3.2.9 on 2021-11-06 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0005_alter_subject_subject_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='address',
            field=models.CharField(blank=True, default=None, max_length=50, verbose_name='Сетевой адрес субъекта'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='secret_key',
            field=models.CharField(blank=True, default=None, max_length=50, verbose_name='Секретный ключ субъекта(для подтверждения личности)'),
        ),
    ]
