# Generated by Django 3.2.9 on 2021-11-06 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0006_auto_20211106_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historygetkey',
            name='object',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='object_list', to='reg.subject', verbose_name='Имя объекта'),
        ),
    ]
