# Generated by Django 3.2.9 on 2021-11-06 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0007_alter_historygetkey_object'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='address',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Сетевой адрес субъекта'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='secret_key',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Секретный ключ субъекта(для подтверждения личности)'),
        ),
    ]
