# Generated by Django 3.2.9 on 2021-11-20 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0009_auto_20211120_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='key',
            name='type',
            field=models.CharField(blank=True, choices=[('Ключ регистрационного центра', 'Reg'), ('Ключ сертификационного центра', 'Cert')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='key',
            name='private_key',
            field=models.FileField(blank=True, null=True, upload_to='private'),
        ),
        migrations.AlterField(
            model_name='key',
            name='public_key',
            field=models.FileField(blank=True, null=True, upload_to='public'),
        ),
    ]
