# Generated by Django 3.2.9 on 2021-11-24 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0010_auto_20211120_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='as',
            name='signature',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='Цифровая электронная подпись сертификата'),
        ),
    ]
