# Generated by Django 3.2.9 on 2021-11-05 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InfoCancellation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revocation_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата получения запроса об аннулировании')),
                ('reason_code', models.CharField(blank=True, choices=[('1', 'Причина не определена'), ('2', 'Повреждение ключа конечного пользователя'), ('3', 'Повреждение ключа УЦ'), ('4', 'Изменение информации в сертификате(не повреждение)'), ('5', 'Приостановление действия ключа'), ('6', 'Завершение использования'), ('7', 'Приостановление использования'), ('8', 'Отмена временного приостановления')], max_length=5, null=True, verbose_name='Код причины аннулирования')),
                ('hold_instruction_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='Код временного приостановления сертификата (OID)')),
                ('invalidity_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата признания сертификата недействительным')),
                ('certificate_issuer', models.CharField(blank=True, max_length=50, null=True, verbose_name='Имя издателя сертификата, ассоциированного с косвенным САС')),
            ],
            options={
                'verbose_name': 'Причина аннулирования сертификата',
                'verbose_name_plural': 'Причины аннулирования сертификата',
            },
        ),
        migrations.CreateModel(
            name='Key',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_key', models.FileField(upload_to='public')),
                ('private_key', models.FileField(upload_to='private')),
                ('active', models.BooleanField(blank=True, default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(blank=True, default='1', max_length=20, verbose_name='Версия сертификата')),
                ('serial_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Серийный номер сертификата')),
                ('id_algorithm_signature', models.CharField(blank=True, max_length=50, null=True, verbose_name='Идентификатор алгоритма цифровой подписи')),
                ('publisher_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Имя издателя')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='Дата начала действия сертификата')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Дата конца действия сертификата')),
                ('subject_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Имя субъекта сертификата')),
                ('public_key', models.CharField(blank=True, max_length=200, null=True, verbose_name='Публичный ключ субъекта')),
                ('id_publisher', models.CharField(blank=True, max_length=200, null=True, verbose_name='Уникальный идентификатор издателя')),
                ('id_subject', models.CharField(blank=True, max_length=200, null=True, verbose_name='Уникальный идентификатор субъекта')),
                ('active', models.BooleanField(blank=True, default=True, verbose_name='Указывает, является ли сертификат действующим')),
                ('info_cancellation', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to='cert.infocancellation', verbose_name='Информация об аннулировании')),
            ],
            options={
                'verbose_name': 'Сертификат',
                'verbose_name_plural': 'Сертификаты',
            },
        ),
    ]
