# Generated by Django 3.2.9 on 2021-11-05 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cert', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infocancellation',
            name='certificate_issuer',
        ),
    ]
